"""added email to org

Revision ID: 38cf92de8735
Revises: 5a8b31911e73
Create Date: 2014-10-09 00:41:42.050673

"""

# revision identifiers, used by Alembic.
revision = '38cf92de8735'
down_revision = '5a8b31911e73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_info', sa.Column('email', sa.Unicode(length=254), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_info', 'email')
    ### end Alembic commands ###
