"""make user_id non nullable

Revision ID: 52d4ac88a01f
Revises: 38cf92de8735
Create Date: 2014-10-09 01:44:24.929168

"""

# revision identifiers, used by Alembic.
revision = '52d4ac88a01f'
down_revision = '38cf92de8735'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
