"""added org details

Revision ID: 5a8b31911e73
Revises: 27e08b47eb86
Create Date: 2014-10-08 01:52:11.279655

"""

# revision identifiers, used by Alembic.
revision = '5a8b31911e73'
down_revision = '27e08b47eb86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.Column('title', sa.Unicode(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('website', sa.Unicode(length=500), nullable=True),
    sa.Column('facebook', sa.Unicode(length=500), nullable=True),
    sa.Column('blog', sa.Unicode(length=500), nullable=True),
    sa.Column('has_80g_certificate', sa.Boolean(), nullable=False),
    sa.Column('person1_name', sa.Unicode(length=160), nullable=True),
    sa.Column('person1_position', sa.Unicode(length=160), nullable=True),
    sa.Column('person1_email', sa.Unicode(length=254), nullable=True),
    sa.Column('person1_phone', sa.Unicode(length=15), nullable=True),
    sa.Column('person2_name', sa.Unicode(length=160), nullable=True),
    sa.Column('person2_position', sa.Unicode(length=160), nullable=True),
    sa.Column('person2_email', sa.Unicode(length=254), nullable=True),
    sa.Column('person2_phone', sa.Unicode(length=15), nullable=True),
    sa.Column('intro', sa.Unicode(length=10000), nullable=True),
    sa.Column('total_impact_on_children', sa.Integer(), nullable=True),
    sa.Column('age_group_of_children', sa.Unicode(length=20), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_work')
    op.drop_table('organization_info')
    op.drop_table('organization')
    ### end Alembic commands ###
